version: "3.8"
services:
  backend:
    build: ./backend
    container_name: travel_backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/travel_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: travel_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: travel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
